name: Upload to NHN Cloud Object Storage

on:
  push:
    branches:
      - main

jobs:
  upload-to-object-storage:
    runs-on: ubuntu-latest
    steps:
      # 코드 체크아웃
      - name: Checkout repository
        uses: actions/checkout@v3

      # 업로드할 파일 생성
      - name: Generate a file
        run: echo "Hello NHN Cloud Object Storage!" > aws_with_action.txt

      # 토큰 발급
      - name: Generate Auth Token
        id: get_token
        run: |
          AUTH_RESPONSE=$(curl -s -X POST https://api-identity-infrastructure.nhncloudservice.com/v2.0/tokens \
          -H "Content-Type: application/json" \
          -d '{
                "auth": {
                    "tenantId": "66ac27acad5e42f3b92842a8a4e217b2",
                    "passwordCredentials": {
                        "username": "giun@netsoultech.com",
                        "password": "1234"
                    }
                }
            }')
      
          TOKEN=$(echo "$AUTH_RESPONSE" | jq -r '.access.token.id')
          echo "TOKEN=$TOKEN" >> $GITHUB_ENV
      
      # 크레덴셜 조회
      - name: get NHN Cloud Credentials
        id: get-credentials
        run: |
          response=$(curl -X GET \
            https://api-identity-infrastructure.nhncloudservice.com/v2.0/users/85cea4fd8e674fb484b944dae202a820/credentials/OS-EC2 \
            -H "X-Auth-Token: ${{ env.TOKEN }}")
          
          echo "ACCESS_KEY=$(echo $response | jq -r '.credentials[0].access')" >> $GITHUB_ENV
          echo "SECRET_KEY=$(echo $response | jq -r '.credentials[0].secret')" >> $GITHUB_ENV

      # 크레덴셜 정보 확인
      - name: Debug credential variables
        run: |
          echo "Access Key: ${{ env.ACCESS_KEY }}"
          echo "Secret Key: ${{ env.SECRET_KEY }}"

      # AWS CLI 설치
      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli
          
      # AWS의 버전을 확인
      - name: Show AWS CLI version
        run: |
          aws --version
          
      # NHN Cloud Object Storage에 업로드
      - name: Upload file to NHN Cloud Object Storage
        run: |
          aws --endpoint-url=https://kr1-api-object-storage.nhncloudservice.com s3 cp aws_with_action.txt s3://obj-test/aws_with_action.txt
        env:
          AWS_ACCESS_KEY_ID: ${{ env.ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ env.SECRET_KEY }}
          AWS_EC2_METADATA_DISABLED: true
